FORMAT: 1A
HOST: https://localhost:8080/

# Moi_Sklad_API_app

API приложения.

## Запрос на создание товара [/newproduct]

### Создать товар [POST]

Создать товар - на /newproduct подается уникальное наименование товара.

+ Request (application/json)

        {
            "model": "наименование товара",
        }
        
+ Response 200 (text/html)

        Данная модель успешно добавлена в базу данных.
        
+ Response 400 (text/html)

        Данная модель уже добавлена в базу данных.
        
        
## Запрос на закупку товара [/purchase]
### Закупить товар [POST]

Закупить товар – на /purchase подается наименование товара, кол-во
закупленного товара, цена единицы товара и дата закупки.


+ Request (application/json)

        {
            "model": "наименование товара",
            "quantity": "количество товара",
            "price": "цена закупки единицы товара",
            "date": "дата в формате yyyy.MM.dd"
        }

+ Response 200 (text/html)

   Закупка успешно добавлена в базу данных.
   
+ Response 400 (text/html)

    Данная модель уже добавлена в базу данных.
    
## Запрос на продажу товара [/demand]
### Продать товар [POST]

Продать товар – на /demand подается наименование товара, кол-во
проданного товара, цена единицы товара и дата продажи.

+ Request (application/json)

        {
            "model": "наименование товара",
            "quantity": "количество товара",
            "price": "цена продажи единицы товара",
            "date": "дата в формате yyyy.MM.dd"
        }

+ Response 200 (text/html)

   {
        "income": прибыль с продажи
   }
   
+ Response 400 (text/html)

    Неверное количество товара.

## Запрос на расчет прибыльности товара за период до указанной даты [/salesreport]
### Рассчитать прибыльность [POST]

На /salesreport подается наименование
товара и дата. Результат – прибыль на указанную дату – выводится в стандартный
поток вывода.

+ Request (application/json)

        {
            "model": "наименование товара",
            "date": "дата в формате yyyy.MM.dd"
        }

+ Response 200 (text/html)
    
   Замечательно, наша прибыль = ...
   
+ Response 400 (text/html)

    Неверные данные...


















